### ISSUE TITLE
Default theming has white text on white background

### ISSUE THREAD

**Issue by jonashertzman** [GMPrakhar/MAUI-Designer#11]
I'm getting this when when I'm running the project in Visual Studio

![image](https://github.com/user-attachments/assets/104545d3-1b40-419c-9bd4-612300aba7ee)

No idea why it does not look the screen shots in the readme.

**Comment by GMPrakhar** [comment]
I have my machine theme setup as Dark, probably that might be contributing to it, but ideally theme changes should have been handled directly by MAUI. Let me check this.

**Comment by GMPrakhar** [comment]
@jonashertzman : I have fixed the issue where some colors were hardcoded. Can you please check now?

**Comment by jonashertzman** [comment]
Yes, that fixed the problem.

![image](https://github.com/user-attachments/assets/674f0ac9-755b-4b39-8050-2e72bb63d894)
![image](https://github.com/user-attachments/assets/a7ec9dce-c472-4452-9ec2-86c3fc279f93)
